import { useState, useEffect } from 'react';
import { FileSpreadsheet, FileText, Download, Calendar, Filter } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { useAuth } from '@/contexts/AuthContext';
import { auditAPI, adminAPI } from '@/lib/api';
import { useToast } from '@/hooks/use-toast';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const AuditReports = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [auditData, setAuditData] = useState<any>(null);
  const [stats, setStats] = useState<any>({
    faculty: { total: 0 },
    fdps: { pending: 0, approved: 0, rejected: 0, total: 0 },
    reimbursements: { total: 0, pending: 0, approved: 0, totalAmount: 0 },
    achievements: { verified: 0 },
    internships: { ongoing: 0, completed: 0, total: 0 },
    period: { startDate: 'all time', endDate: 'all time' },
  });
  const [loading, setLoading] = useState(false);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [selectedDepartment, setSelectedDepartment] = useState('');
  const [departments, setDepartments] = useState<string[]>([]);

  useEffect(() => {
    loadStats();
    loadDepartments();
    loadAuditData();
  }, []);

  const loadDepartments = async () => {
    try {
      const faculty = await adminAPI.getFaculty();
      const deptSet = new Set(faculty.map((f: any) => f.department).filter(Boolean));
      setDepartments(Array.from(deptSet));
    } catch (error) {
      console.error('Failed to load departments:', error);
    }
  };

  const loadStats = async () => {
    try {
      setLoading(true);
      const data = await auditAPI.getAuditStats({
        startDate: startDate || undefined,
        endDate: endDate || undefined,
        department: selectedDepartment || undefined,
      });
      setStats(data || {
        faculty: { total: 0 },
        fdps: { pending: 0, approved: 0, rejected: 0, total: 0 },
        reimbursements: { total: 0, pending: 0, approved: 0, totalAmount: 0 },
        achievements: { verified: 0 },
        internships: { ongoing: 0, completed: 0, total: 0 },
        period: { startDate: 'all time', endDate: 'all time' },
      });
    } catch (error) {
      console.error('Failed to load stats:', error);
      toast({ title: 'Failed to load statistics', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  const loadAuditData = async () => {
    try {
      setLoading(true);
      const data = await auditAPI.getAuditData({
        startDate: startDate || undefined,
        endDate: endDate || undefined,
        department: selectedDepartment || undefined,
      });
      setAuditData(data);
      toast({ title: 'Audit data loaded successfully' });
    } catch (error) {
      console.error('Failed to load audit data:', error);
      toast({ title: 'Failed to load audit data', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  };

  const handleFilter = () => {
    loadStats();
  };

  const downloadExcel = async () => {
    if (!auditData) {
      toast({ title: 'Please load audit data first', variant: 'destructive' });
      return;
    }

    try {
      const workbook = XLSX.utils.book_new();

      // Summary Sheet
      const summaryData = [
        ['Audit Report Summary'],
        ['Generated On', new Date().toLocaleString()],
        ['Generated By', auditData.generatedBy?.name || 'N/A'],
        ['Role', auditData.generatedBy?.role || 'N/A'],
        [],
        ['Total Faculty', auditData.summary.totalFaculty],
        ['Total FDP Attended', auditData.summary.totalFDPAttended],
        ['Total FDP Organized', auditData.summary.totalFDPOrganized],
        ['Total Seminars', auditData.summary.totalSeminars],
        ['Total ABL', auditData.summary.totalABL],
        ['Total Joint Teaching', auditData.summary.totalJointTeaching],
        ['Total Adjunct Faculty', auditData.summary.totalAdjunctFaculty],
        ['Total Reimbursements', auditData.summary.totalReimbursements],
        ['Total Reimbursement Amount', auditData.summary.totalReimbursementAmount],
        ['Total Achievements', auditData.summary.totalAchievements],
        ['Total Internships', auditData.summary.totalInternships],
      ];

      const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

      // Faculty Sheet
      if (auditData.data.faculty.length > 0) {
        const facultySheet = XLSX.utils.json_to_sheet(
          auditData.data.faculty.map((f: any) => ({
            'Name': f.name,
            'Email': f.email,
            'Department': f.department,
            'Designation': f.designation,
          }))
        );
        XLSX.utils.book_append_sheet(workbook, facultySheet, 'Faculty');
      }

      // FDP Attended Sheet
      if (auditData.data.fdpAttended.length > 0) {
        const fdpSheet = XLSX.utils.json_to_sheet(
          auditData.data.fdpAttended.map((f: any) => ({
            'Faculty': f.facultyId?.name || 'N/A',
            'Title': f.title,
            'Mode': f.mode,
            'Duration': f.duration,
            'Venue': f.venue,
            'Status': f.status,
          }))
        );
        XLSX.utils.book_append_sheet(workbook, fdpSheet, 'FDP Attended');
      }

      // Reimbursements Sheet
      if (auditData.data.reimbursements.length > 0) {
        const reimbSheet = XLSX.utils.json_to_sheet(
          auditData.data.reimbursements.map((r: any) => ({
            'Faculty': r.facultyId?.name || 'N/A',
            'FDP Title': r.fdpTitle,
            'Amount': r.amount,
            'Type': r.expenseType,
            'Status': r.status,
          }))
        );
        XLSX.utils.book_append_sheet(workbook, reimbSheet, 'Reimbursements');
      }

      // Achievements Sheet
      if (auditData.data.achievements.length > 0) {
        const achSheet = XLSX.utils.json_to_sheet(
          auditData.data.achievements.map((a: any) => ({
            'Faculty': a.facultyId?.name || 'N/A',
            'Title': a.title,
            'Category': a.category,
            'Issuer': a.issuer,
            'Date': a.date ? new Date(a.date).toLocaleDateString() : 'N/A',
            'Status': a.status,
          }))
        );
        XLSX.utils.book_append_sheet(workbook, achSheet, 'Achievements');
      }

      // Internships Sheet
      if (auditData.data.internships.length > 0) {
        const intSheet = XLSX.utils.json_to_sheet(
          auditData.data.internships.map((i: any) => ({
            'Faculty': i.facultyId?.name || 'N/A',
            'Student': i.studentName,
            'Company': i.companyName,
            'Position': i.position,
            'Status': i.status,
          }))
        );
        XLSX.utils.book_append_sheet(workbook, intSheet, 'Internships');
      }

      const fileName = `Audit_Report_${new Date().toISOString().split('T')[0]}.xlsx`;
      XLSX.writeFile(workbook, fileName);
      toast({ title: 'Excel report downloaded successfully' });
    } catch (error) {
      console.error('Failed to generate Excel:', error);
      toast({ title: 'Failed to generate Excel report', variant: 'destructive' });
    }
  };

  const downloadPDF = async () => {
    if (!auditData) {
      toast({ title: 'Please load audit data first', variant: 'destructive' });
      return;
    }

    try {
      const doc = new jsPDF();
      let yPos = 20;

      // Title
      doc.setFontSize(18);
      doc.text('Comprehensive Audit Report', 14, yPos);
      yPos += 10;

      // Metadata
      doc.setFontSize(11);
      doc.text(`Generated On: ${new Date().toLocaleString()}`, 14, yPos);
      yPos += 5;
      doc.text(`Generated By: ${auditData.generatedBy?.name || 'N/A'} (${auditData.generatedBy?.role || 'N/A'})`, 14, yPos);
      yPos += 10;

      // Summary
      doc.setFontSize(14);
      doc.text('Summary', 14, yPos);
      yPos += 8;

      autoTable(doc, {
        startY: yPos,
        head: [['Category', 'Count']],
        body: [
          ['Total Faculty', auditData.summary.totalFaculty],
          ['FDP Attended', auditData.summary.totalFDPAttended],
          ['FDP Organized', auditData.summary.totalFDPOrganized],
          ['Seminars', auditData.summary.totalSeminars],
          ['ABL', auditData.summary.totalABL],
          ['Joint Teaching', auditData.summary.totalJointTeaching],
          ['Adjunct Faculty', auditData.summary.totalAdjunctFaculty],
          ['Reimbursements', auditData.summary.totalReimbursements],
          ['Total Reimbursement Amount', auditData.summary.totalReimbursementAmount],
          ['Achievements', auditData.summary.totalAchievements],
          ['Internships', auditData.summary.totalInternships],
        ],
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246] },
      });

      yPos = (doc as any).lastAutoTable.finalY + 15;

      // Reimbursements Table
      if (auditData.data.reimbursements.length > 0) {
        doc.addPage();
        doc.setFontSize(14);
        doc.text('Reimbursements', 14, 20);

        autoTable(doc, {
          startY: 30,
          head: [['Faculty', 'FDP Title', 'Amount', 'Type', 'Status']],
          body: auditData.data.reimbursements.map((r: any) => [
            r.facultyId?.name || 'N/A',
            r.fdpTitle,
            `${r.currency || 'INR'} ${r.amount}`,
            r.expenseType,
            r.status,
          ]),
          theme: 'grid',
          headStyles: { fillColor: [59, 130, 246] },
        });
      }

      const fileName = `Audit_Report_${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);
      toast({ title: 'PDF report downloaded successfully' });
    } catch (error) {
      console.error('Failed to generate PDF:', error);
      toast({ title: 'Failed to generate PDF report', variant: 'destructive' });
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Audit & Reports</h1>
          <p className="text-muted-foreground">Generate comprehensive audit reports and statistics</p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Filter className="h-5 w-5" />
            Filters
          </CardTitle>
          <CardDescription>Filter audit data by date range and department</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div>
              <Label htmlFor="startDate">Start Date</Label>
              <Input
                id="startDate"
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
              />
            </div>
            <div>
              <Label htmlFor="endDate">End Date</Label>
              <Input
                id="endDate"
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
              />
            </div>
            {user?.role === 'admin' && (
              <div>
                <Label htmlFor="department">Department</Label>
                <Select value={selectedDepartment} onValueChange={setSelectedDepartment}>
                  <SelectTrigger>
                    <SelectValue placeholder="All Departments" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">All Departments</SelectItem>
                    {departments.map((dept) => (
                      <SelectItem key={dept} value={dept}>{dept}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
            <div className="flex items-end">
              <Button onClick={handleFilter} className="w-full">
                <Filter className="mr-2 h-4 w-4" />
                Apply Filters
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Total Faculty</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats?.faculty?.total ?? 0}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Pending FDPs</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats?.fdps?.pending ?? 0}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Total Reimbursements</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats?.reimbursements?.total ?? 0}</div>
            <p className="text-xs text-muted-foreground">
              Amount: ₹{Number(stats?.reimbursements?.totalAmount ?? 0).toLocaleString()}
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">Verified Achievements</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{stats?.achievements?.verified ?? 0}</div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Generate Reports</CardTitle>
              <CardDescription>Download comprehensive audit reports in PDF or Excel format</CardDescription>
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={loadAuditData}
                disabled={loading}
              >
                <Download className="mr-2 h-4 w-4" />
                Load Audit Data
              </Button>
              <Button
                variant="outline"
                onClick={downloadExcel}
                disabled={!auditData || loading}
              >
                <FileSpreadsheet className="mr-2 h-4 w-4" />
                Export Excel
              </Button>
              <Button
                variant="outline"
                onClick={downloadPDF}
                disabled={!auditData || loading}
              >
                <FileText className="mr-2 h-4 w-4" />
                Export PDF
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {loading && (
            <div className="text-center py-8">Loading audit data...</div>
          )}
          {auditData && !loading && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">Faculty</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalFaculty}</div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">FDP Attended</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalFDPAttended}</div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">FDP Organized</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalFDPOrganized}</div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">Seminars</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalSeminars}</div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">ABL Activities</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalABL}</div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">Joint Teaching</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalJointTeaching}</div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">Adjunct Faculty</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalAdjunctFaculty}</div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">Reimbursements</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalReimbursements}</div>
                  <div className="text-xs text-muted-foreground">
                    ₹{auditData.summary.totalReimbursementAmount.toLocaleString()}
                  </div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">Achievements</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalAchievements}</div>
                </div>
                <div className="p-4 border rounded-lg">
                  <div className="text-sm text-muted-foreground">Internships</div>
                  <div className="text-2xl font-bold">{auditData.summary.totalInternships}</div>
                </div>
              </div>
              <div className="text-sm text-muted-foreground">
                Report includes all modules: FDPs, Seminars, ABL, Joint Teaching, Adjunct Faculty, Reimbursements, Achievements, and Internships
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default AuditReports;
